# Generated by Django 4.1 on 2023-09-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_inventoryrecord_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecord',
            name='delete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
