# Generated by Django 4.1 on 2023-09-11 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_trydatabase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TryDatabase',
        ),
    ]
